import Head from "next/head";

import Hero from "../components/Hero";
import JoinCohort from "../components/JoinCohort";
import Practicality from "../components/Practicality";
import WhyInnovatics from "../components/WhyInnovatics";
import OnDemandSection from "../components/OnDemandSection";
import LearningsSections from "../components/LearningsSections";
import FeaturedSection from "../components/FeaturedSection";
import CoursesSection from "../components/CoursesSection";
import PricingSection from "../components/PricingSection";
import LiveSection from "../components/LiveSection";
import CareerTalksSection from "../components/CareerTalksSection";
import JoinDiscord from "../components/JoinDiscord";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Innovatics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <JoinCohort />
      <Practicality />
      <WhyInnovatics />
      <OnDemandSection />
      <LearningsSections />
      <FeaturedSection />
      <CoursesSection />
      <PricingSection />
      <LiveSection />
      <CareerTalksSection />
      <JoinDiscord />
    </div>
  );
}
