name: Deploy to VPS

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST: ${{ secrets.HOST }}
  USER: ${{ secrets.USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug info
        run: |
          echo "Host: $HOST ==== ${{ secrets.HOST }}"
          echo "User: $USER  === ${{ secrets.USER }}"
          echo "Key: $SSH_PRIVATE_KEY   === ${{ secrets.USER }}"

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "success" > text.txt

